.TH srslyd.8 "srslyd"
.SH NAME
.B srslyd
\ - SPF verification daemon with SRS support
.SH SYNOPSIS
.B srslyd
[configfile]
.SH DESCRIPTION
.B srslyd
is a
.I milter
-based daemon application that implements
.B SPF
verifications and
.B SRS
address rewriting on redirects.

.SH OPERATION

.B srslyd
must be started as
.I root.
It will create a
