#!/bin/sh

set -e

case "$1" in
    purge|remove)
      deluser --quiet --system srsly > /dev/null || true
      delgroup --quiet --system srsly > /dev/null || true
      rm -f /var/run/srslyd.pid /var/run/srsly.socket
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
